// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kpcYe-haxaw4CPR67QN_Smg4vJr6ZRQ',
    appId: '1:663430248806:web:6d085980aeaebfae64f0a7',
    messagingSenderId: '663430248806',
    projectId: 'likhwao-15dcc',
    authDomain: 'likhwao-15dcc.firebaseapp.com',
    storageBucket: 'likhwao-15dcc.firebasestorage.app',
    measurementId: 'G-2PX74MLXWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFkh_x3q-lEjibDHtJIvJzqYO0MQw1Shg',
    appId: '1:663430248806:android:34e857ab70c0a3a364f0a7',
    messagingSenderId: '663430248806',
    projectId: 'likhwao-15dcc',
    storageBucket: 'likhwao-15dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXv_IDGkXHH38vXGeGEOc7-No6AIsIqd0',
    appId: '1:663430248806:ios:da7e06948bbe3a1764f0a7',
    messagingSenderId: '663430248806',
    projectId: 'likhwao-15dcc',
    storageBucket: 'likhwao-15dcc.firebasestorage.app',
    iosBundleId: 'com.example.adminlikhwao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXv_IDGkXHH38vXGeGEOc7-No6AIsIqd0',
    appId: '1:663430248806:ios:da7e06948bbe3a1764f0a7',
    messagingSenderId: '663430248806',
    projectId: 'likhwao-15dcc',
    storageBucket: 'likhwao-15dcc.firebasestorage.app',
    iosBundleId: 'com.example.adminlikhwao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBskn03ON1Ib-B_1Tr-jBIVieMM0PMYc8k',
    appId: '1:663430248806:web:835a54f7f209444164f0a7',
    messagingSenderId: '663430248806',
    projectId: 'likhwao-15dcc',
    authDomain: 'likhwao-15dcc.firebaseapp.com',
    storageBucket: 'likhwao-15dcc.firebasestorage.app',
    measurementId: 'G-DLFTP45LE6',
  );
}
